sudo: false
language: go
os: osx
go:
  - stable
matrix:
  include:
  - os: osx
    osx_image: xcode10.1
  fast_finish: true
before_install:
  - go get github.com/mitchellh/gox
install:
  - # skip
before_script:
  - if which sw_vers; then sw_vers; fi
  - go get -u golang.org/x/lint/golint
script:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
  - gox -os="darwin" -arch="amd64" -output="app-quarantine_{{.OS}}_{{.Arch}}" -ldflags "-X github.com/patsoffice/app-quarantine/v2/cmd.Rev=`git rev-parse --short HEAD` -X github.com/patsoffice/app-quarantine/v2/cmd.Ver=$TRAVIS_BRANCH" -verbose ./...
after_script:
  - test -z "$(gofmt -s -l -w . | tee /dev/stderr)"
  - test -z "$(golint ./...     | tee /dev/stderr)"
  - go vet ./...
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: PRVSx2KWdx5S2Y/G0XCniY0jBK00XVTKZAh7VexAUMCwwoWbYtrwvqQLQv7J7MkVKypqtmEGzze2GUUeCMgaRMkL9PVRpTySKa3iETPza8z8zW2x25QtqGHRjQJP/iIcdVrbK+hG4Ns/KcoxXA5o66Dlj44udxnSRjc76tT6u7A8piMq+/CEv2e2T1Yz4fUTrmiT+I8Pc/r335vJF1vNYaND65PmcxCKTGkOXl5ijLJZS0lTZ0tS0+/cWA7lsdKo/N8Qegk1KQVqO65LbbEEBSiVrjyL/zPmXS6v0/nUujOX3Qe7Dls/SCLNkJjU3tlWYYAsedgyF3ECtFz02UYPgHdwm6FcdAA5mbUklL1eoJKALHSptXtq0s70cLc1mBA4xDciUhMxWBbKpKaTmR1C0C2IEh3FvgHVCKCEfcguIGUfVB8R+OrlQhnWPzfT3X3lq1+YWPy/ksysxTNC/Wc5N7WjBi6Rd6oVM8aSa9BCyank04mxw+IGPCiR/4hhsuK6CaYrgIm9sVtqYGhdEKRm84Prlj9JeFaSJqUfSPzHIeM5I9+qrEjKY7Vq6GDboUd1QMObO2qXXissVHWAty0gYYWzHcskc7huO5MjjLdXOdcwgW/6q/RHZ43dNXqlGCawV0Z03QBq9b2xhAGdIqPIgf4LuBmLTNQNqqsD6PZivPU=
  file:
    - app-quarantine_darwin_amd64
  on:
    repo: patsoffice/app-quarantine
    tags: true
